//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interface_vente_ody_c_ines.Log {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthRequest", Namespace="http://webservice.ines.fr")]
    [System.SerializableAttribute()]
    public partial class AuthRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string compteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string compte {
            get {
                return this.compteField;
            }
            set {
                if ((object.ReferenceEquals(this.compteField, value) != true)) {
                    this.compteField = value;
                    this.RaisePropertyChanged("compte");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthResponse", Namespace="http://webservice.ines.fr")]
    [System.SerializableAttribute()]
    public partial class AuthResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idSessionField;
        
        private interface_vente_ody_c_ines.Log.CodeEnum codeReturnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idSession {
            get {
                return this.idSessionField;
            }
            set {
                if ((object.ReferenceEquals(this.idSessionField, value) != true)) {
                    this.idSessionField = value;
                    this.RaisePropertyChanged("idSession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public interface_vente_ody_c_ines.Log.CodeEnum codeReturn {
            get {
                return this.codeReturnField;
            }
            set {
                if ((this.codeReturnField.Equals(value) != true)) {
                    this.codeReturnField = value;
                    this.RaisePropertyChanged("codeReturn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeEnum", Namespace="http://webservice.ines.fr")]
    public enum CodeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        failed = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthContact", Namespace="http://webservice.ines.fr")]
    [System.SerializableAttribute()]
    public partial class AuthContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthContactResponse", Namespace="http://webservice.ines.fr")]
    [System.SerializableAttribute()]
    public partial class AuthContactResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ContactRefField;
        
        private int ClientRefField;
        
        private interface_vente_ody_c_ines.Log.CodeEnum CodeReturnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ContactRef {
            get {
                return this.ContactRefField;
            }
            set {
                if ((this.ContactRefField.Equals(value) != true)) {
                    this.ContactRefField = value;
                    this.RaisePropertyChanged("ContactRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ClientRef {
            get {
                return this.ClientRefField;
            }
            set {
                if ((this.ClientRefField.Equals(value) != true)) {
                    this.ClientRefField = value;
                    this.RaisePropertyChanged("ClientRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public interface_vente_ody_c_ines.Log.CodeEnum CodeReturn {
            get {
                return this.CodeReturnField;
            }
            set {
                if ((this.CodeReturnField.Equals(value) != true)) {
                    this.CodeReturnField = value;
                    this.RaisePropertyChanged("CodeReturn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.ines.fr", ConfigurationName="Log.LoginSoap")]
    public interface LoginSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément request de l'espace de noms http://webservice.ines.fr n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/getUserRefWs", ReplyAction="*")]
        interface_vente_ody_c_ines.Log.getUserRefWsResponse getUserRefWs(interface_vente_ody_c_ines.Log.getUserRefWsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/getUserRefWs", ReplyAction="*")]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.getUserRefWsResponse> getUserRefWsAsync(interface_vente_ody_c_ines.Log.getUserRefWsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément request de l'espace de noms http://webservice.ines.fr n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/authenticationWs", ReplyAction="*")]
        interface_vente_ody_c_ines.Log.authenticationWsResponse authenticationWs(interface_vente_ody_c_ines.Log.authenticationWsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/authenticationWs", ReplyAction="*")]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.authenticationWsResponse> authenticationWsAsync(interface_vente_ody_c_ines.Log.authenticationWsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément sessionId de l'espace de noms http://webservice.ines.fr n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/refreshSessionWs", ReplyAction="*")]
        interface_vente_ody_c_ines.Log.refreshSessionWsResponse refreshSessionWs(interface_vente_ody_c_ines.Log.refreshSessionWsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/refreshSessionWs", ReplyAction="*")]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.refreshSessionWsResponse> refreshSessionWsAsync(interface_vente_ody_c_ines.Log.refreshSessionWsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément sessionId de l'espace de noms http://webservice.ines.fr n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/logoutSessionWs", ReplyAction="*")]
        interface_vente_ody_c_ines.Log.logoutSessionWsResponse logoutSessionWs(interface_vente_ody_c_ines.Log.logoutSessionWsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/logoutSessionWs", ReplyAction="*")]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.logoutSessionWsResponse> logoutSessionWsAsync(interface_vente_ody_c_ines.Log.logoutSessionWsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément request de l'espace de noms http://webservice.ines.fr n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/getControlId", ReplyAction="*")]
        interface_vente_ody_c_ines.Log.getControlIdResponse getControlId(interface_vente_ody_c_ines.Log.getControlIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/getControlId", ReplyAction="*")]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.getControlIdResponse> getControlIdAsync(interface_vente_ody_c_ines.Log.getControlIdRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément sessionId de l'espace de noms http://webservice.ines.fr n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/contactAuthentication", ReplyAction="*")]
        interface_vente_ody_c_ines.Log.contactAuthenticationResponse contactAuthentication(interface_vente_ody_c_ines.Log.contactAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/contactAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.contactAuthenticationResponse> contactAuthenticationAsync(interface_vente_ody_c_ines.Log.contactAuthenticationRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément sessionId de l'espace de noms http://webservice.ines.fr n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/contactChangePassword", ReplyAction="*")]
        interface_vente_ody_c_ines.Log.contactChangePasswordResponse contactChangePassword(interface_vente_ody_c_ines.Log.contactChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ines.fr/contactChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.contactChangePasswordResponse> contactChangePasswordAsync(interface_vente_ody_c_ines.Log.contactChangePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserRefWsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserRefWs", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.getUserRefWsRequestBody Body;
        
        public getUserRefWsRequest() {
        }
        
        public getUserRefWsRequest(interface_vente_ody_c_ines.Log.getUserRefWsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class getUserRefWsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public interface_vente_ody_c_ines.Log.AuthRequest request;
        
        public getUserRefWsRequestBody() {
        }
        
        public getUserRefWsRequestBody(interface_vente_ody_c_ines.Log.AuthRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserRefWsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserRefWsResponse", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.getUserRefWsResponseBody Body;
        
        public getUserRefWsResponse() {
        }
        
        public getUserRefWsResponse(interface_vente_ody_c_ines.Log.getUserRefWsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class getUserRefWsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getUserRefWsResult;
        
        public getUserRefWsResponseBody() {
        }
        
        public getUserRefWsResponseBody(int getUserRefWsResult) {
            this.getUserRefWsResult = getUserRefWsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticationWsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticationWs", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.authenticationWsRequestBody Body;
        
        public authenticationWsRequest() {
        }
        
        public authenticationWsRequest(interface_vente_ody_c_ines.Log.authenticationWsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class authenticationWsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public interface_vente_ody_c_ines.Log.AuthRequest request;
        
        public authenticationWsRequestBody() {
        }
        
        public authenticationWsRequestBody(interface_vente_ody_c_ines.Log.AuthRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticationWsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticationWsResponse", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.authenticationWsResponseBody Body;
        
        public authenticationWsResponse() {
        }
        
        public authenticationWsResponse(interface_vente_ody_c_ines.Log.authenticationWsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class authenticationWsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public interface_vente_ody_c_ines.Log.AuthResponse authenticationWsResult;
        
        public authenticationWsResponseBody() {
        }
        
        public authenticationWsResponseBody(interface_vente_ody_c_ines.Log.AuthResponse authenticationWsResult) {
            this.authenticationWsResult = authenticationWsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class refreshSessionWsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="refreshSessionWs", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.refreshSessionWsRequestBody Body;
        
        public refreshSessionWsRequest() {
        }
        
        public refreshSessionWsRequest(interface_vente_ody_c_ines.Log.refreshSessionWsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class refreshSessionWsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        public refreshSessionWsRequestBody() {
        }
        
        public refreshSessionWsRequestBody(string sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class refreshSessionWsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="refreshSessionWsResponse", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.refreshSessionWsResponseBody Body;
        
        public refreshSessionWsResponse() {
        }
        
        public refreshSessionWsResponse(interface_vente_ody_c_ines.Log.refreshSessionWsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class refreshSessionWsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public interface_vente_ody_c_ines.Log.CodeEnum refreshSessionWsResult;
        
        public refreshSessionWsResponseBody() {
        }
        
        public refreshSessionWsResponseBody(interface_vente_ody_c_ines.Log.CodeEnum refreshSessionWsResult) {
            this.refreshSessionWsResult = refreshSessionWsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutSessionWsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutSessionWs", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.logoutSessionWsRequestBody Body;
        
        public logoutSessionWsRequest() {
        }
        
        public logoutSessionWsRequest(interface_vente_ody_c_ines.Log.logoutSessionWsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class logoutSessionWsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        public logoutSessionWsRequestBody() {
        }
        
        public logoutSessionWsRequestBody(string sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutSessionWsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutSessionWsResponse", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.logoutSessionWsResponseBody Body;
        
        public logoutSessionWsResponse() {
        }
        
        public logoutSessionWsResponse(interface_vente_ody_c_ines.Log.logoutSessionWsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class logoutSessionWsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public interface_vente_ody_c_ines.Log.CodeEnum logoutSessionWsResult;
        
        public logoutSessionWsResponseBody() {
        }
        
        public logoutSessionWsResponseBody(interface_vente_ody_c_ines.Log.CodeEnum logoutSessionWsResult) {
            this.logoutSessionWsResult = logoutSessionWsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getControlIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getControlId", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.getControlIdRequestBody Body;
        
        public getControlIdRequest() {
        }
        
        public getControlIdRequest(interface_vente_ody_c_ines.Log.getControlIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class getControlIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public interface_vente_ody_c_ines.Log.AuthRequest request;
        
        public getControlIdRequestBody() {
        }
        
        public getControlIdRequestBody(interface_vente_ody_c_ines.Log.AuthRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getControlIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getControlIdResponse", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.getControlIdResponseBody Body;
        
        public getControlIdResponse() {
        }
        
        public getControlIdResponse(interface_vente_ody_c_ines.Log.getControlIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class getControlIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getControlIdResult;
        
        public getControlIdResponseBody() {
        }
        
        public getControlIdResponseBody(int getControlIdResult) {
            this.getControlIdResult = getControlIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contactAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contactAuthentication", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.contactAuthenticationRequestBody Body;
        
        public contactAuthenticationRequest() {
        }
        
        public contactAuthenticationRequest(interface_vente_ody_c_ines.Log.contactAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class contactAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public interface_vente_ody_c_ines.Log.AuthContact request;
        
        public contactAuthenticationRequestBody() {
        }
        
        public contactAuthenticationRequestBody(string sessionId, interface_vente_ody_c_ines.Log.AuthContact request) {
            this.sessionId = sessionId;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contactAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contactAuthenticationResponse", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.contactAuthenticationResponseBody Body;
        
        public contactAuthenticationResponse() {
        }
        
        public contactAuthenticationResponse(interface_vente_ody_c_ines.Log.contactAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class contactAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public interface_vente_ody_c_ines.Log.AuthContactResponse contactAuthenticationResult;
        
        public contactAuthenticationResponseBody() {
        }
        
        public contactAuthenticationResponseBody(interface_vente_ody_c_ines.Log.AuthContactResponse contactAuthenticationResult) {
            this.contactAuthenticationResult = contactAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contactChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contactChangePassword", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.contactChangePasswordRequestBody Body;
        
        public contactChangePasswordRequest() {
        }
        
        public contactChangePasswordRequest(interface_vente_ody_c_ines.Log.contactChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class contactChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int contactReference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newPassword;
        
        public contactChangePasswordRequestBody() {
        }
        
        public contactChangePasswordRequestBody(string sessionId, int contactReference, string password, string newPassword) {
            this.sessionId = sessionId;
            this.contactReference = contactReference;
            this.password = password;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contactChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contactChangePasswordResponse", Namespace="http://webservice.ines.fr", Order=0)]
        public interface_vente_ody_c_ines.Log.contactChangePasswordResponseBody Body;
        
        public contactChangePasswordResponse() {
        }
        
        public contactChangePasswordResponse(interface_vente_ody_c_ines.Log.contactChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.ines.fr")]
    public partial class contactChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public interface_vente_ody_c_ines.Log.CodeEnum contactChangePasswordResult;
        
        public contactChangePasswordResponseBody() {
        }
        
        public contactChangePasswordResponseBody(interface_vente_ody_c_ines.Log.CodeEnum contactChangePasswordResult) {
            this.contactChangePasswordResult = contactChangePasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSoapChannel : interface_vente_ody_c_ines.Log.LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<interface_vente_ody_c_ines.Log.LoginSoap>, interface_vente_ody_c_ines.Log.LoginSoap {
        
        public LoginSoapClient() {
        }
        
        public LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        interface_vente_ody_c_ines.Log.getUserRefWsResponse interface_vente_ody_c_ines.Log.LoginSoap.getUserRefWs(interface_vente_ody_c_ines.Log.getUserRefWsRequest request) {
            return base.Channel.getUserRefWs(request);
        }
        
        public int getUserRefWs(interface_vente_ody_c_ines.Log.AuthRequest request) {
            interface_vente_ody_c_ines.Log.getUserRefWsRequest inValue = new interface_vente_ody_c_ines.Log.getUserRefWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.getUserRefWsRequestBody();
            inValue.Body.request = request;
            interface_vente_ody_c_ines.Log.getUserRefWsResponse retVal = ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).getUserRefWs(inValue);
            return retVal.Body.getUserRefWsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.getUserRefWsResponse> interface_vente_ody_c_ines.Log.LoginSoap.getUserRefWsAsync(interface_vente_ody_c_ines.Log.getUserRefWsRequest request) {
            return base.Channel.getUserRefWsAsync(request);
        }
        
        public System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.getUserRefWsResponse> getUserRefWsAsync(interface_vente_ody_c_ines.Log.AuthRequest request) {
            interface_vente_ody_c_ines.Log.getUserRefWsRequest inValue = new interface_vente_ody_c_ines.Log.getUserRefWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.getUserRefWsRequestBody();
            inValue.Body.request = request;
            return ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).getUserRefWsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        interface_vente_ody_c_ines.Log.authenticationWsResponse interface_vente_ody_c_ines.Log.LoginSoap.authenticationWs(interface_vente_ody_c_ines.Log.authenticationWsRequest request) {
            return base.Channel.authenticationWs(request);
        }
        
        public interface_vente_ody_c_ines.Log.AuthResponse authenticationWs(interface_vente_ody_c_ines.Log.AuthRequest request) {
            interface_vente_ody_c_ines.Log.authenticationWsRequest inValue = new interface_vente_ody_c_ines.Log.authenticationWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.authenticationWsRequestBody();
            inValue.Body.request = request;
            interface_vente_ody_c_ines.Log.authenticationWsResponse retVal = ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).authenticationWs(inValue);
            return retVal.Body.authenticationWsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.authenticationWsResponse> interface_vente_ody_c_ines.Log.LoginSoap.authenticationWsAsync(interface_vente_ody_c_ines.Log.authenticationWsRequest request) {
            return base.Channel.authenticationWsAsync(request);
        }
        
        public System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.authenticationWsResponse> authenticationWsAsync(interface_vente_ody_c_ines.Log.AuthRequest request) {
            interface_vente_ody_c_ines.Log.authenticationWsRequest inValue = new interface_vente_ody_c_ines.Log.authenticationWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.authenticationWsRequestBody();
            inValue.Body.request = request;
            return ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).authenticationWsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        interface_vente_ody_c_ines.Log.refreshSessionWsResponse interface_vente_ody_c_ines.Log.LoginSoap.refreshSessionWs(interface_vente_ody_c_ines.Log.refreshSessionWsRequest request) {
            return base.Channel.refreshSessionWs(request);
        }
        
        public interface_vente_ody_c_ines.Log.CodeEnum refreshSessionWs(string sessionId) {
            interface_vente_ody_c_ines.Log.refreshSessionWsRequest inValue = new interface_vente_ody_c_ines.Log.refreshSessionWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.refreshSessionWsRequestBody();
            inValue.Body.sessionId = sessionId;
            interface_vente_ody_c_ines.Log.refreshSessionWsResponse retVal = ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).refreshSessionWs(inValue);
            return retVal.Body.refreshSessionWsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.refreshSessionWsResponse> interface_vente_ody_c_ines.Log.LoginSoap.refreshSessionWsAsync(interface_vente_ody_c_ines.Log.refreshSessionWsRequest request) {
            return base.Channel.refreshSessionWsAsync(request);
        }
        
        public System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.refreshSessionWsResponse> refreshSessionWsAsync(string sessionId) {
            interface_vente_ody_c_ines.Log.refreshSessionWsRequest inValue = new interface_vente_ody_c_ines.Log.refreshSessionWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.refreshSessionWsRequestBody();
            inValue.Body.sessionId = sessionId;
            return ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).refreshSessionWsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        interface_vente_ody_c_ines.Log.logoutSessionWsResponse interface_vente_ody_c_ines.Log.LoginSoap.logoutSessionWs(interface_vente_ody_c_ines.Log.logoutSessionWsRequest request) {
            return base.Channel.logoutSessionWs(request);
        }
        
        public interface_vente_ody_c_ines.Log.CodeEnum logoutSessionWs(string sessionId) {
            interface_vente_ody_c_ines.Log.logoutSessionWsRequest inValue = new interface_vente_ody_c_ines.Log.logoutSessionWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.logoutSessionWsRequestBody();
            inValue.Body.sessionId = sessionId;
            interface_vente_ody_c_ines.Log.logoutSessionWsResponse retVal = ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).logoutSessionWs(inValue);
            return retVal.Body.logoutSessionWsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.logoutSessionWsResponse> interface_vente_ody_c_ines.Log.LoginSoap.logoutSessionWsAsync(interface_vente_ody_c_ines.Log.logoutSessionWsRequest request) {
            return base.Channel.logoutSessionWsAsync(request);
        }
        
        public System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.logoutSessionWsResponse> logoutSessionWsAsync(string sessionId) {
            interface_vente_ody_c_ines.Log.logoutSessionWsRequest inValue = new interface_vente_ody_c_ines.Log.logoutSessionWsRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.logoutSessionWsRequestBody();
            inValue.Body.sessionId = sessionId;
            return ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).logoutSessionWsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        interface_vente_ody_c_ines.Log.getControlIdResponse interface_vente_ody_c_ines.Log.LoginSoap.getControlId(interface_vente_ody_c_ines.Log.getControlIdRequest request) {
            return base.Channel.getControlId(request);
        }
        
        public int getControlId(interface_vente_ody_c_ines.Log.AuthRequest request) {
            interface_vente_ody_c_ines.Log.getControlIdRequest inValue = new interface_vente_ody_c_ines.Log.getControlIdRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.getControlIdRequestBody();
            inValue.Body.request = request;
            interface_vente_ody_c_ines.Log.getControlIdResponse retVal = ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).getControlId(inValue);
            return retVal.Body.getControlIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.getControlIdResponse> interface_vente_ody_c_ines.Log.LoginSoap.getControlIdAsync(interface_vente_ody_c_ines.Log.getControlIdRequest request) {
            return base.Channel.getControlIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.getControlIdResponse> getControlIdAsync(interface_vente_ody_c_ines.Log.AuthRequest request) {
            interface_vente_ody_c_ines.Log.getControlIdRequest inValue = new interface_vente_ody_c_ines.Log.getControlIdRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.getControlIdRequestBody();
            inValue.Body.request = request;
            return ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).getControlIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        interface_vente_ody_c_ines.Log.contactAuthenticationResponse interface_vente_ody_c_ines.Log.LoginSoap.contactAuthentication(interface_vente_ody_c_ines.Log.contactAuthenticationRequest request) {
            return base.Channel.contactAuthentication(request);
        }
        
        public interface_vente_ody_c_ines.Log.AuthContactResponse contactAuthentication(string sessionId, interface_vente_ody_c_ines.Log.AuthContact request) {
            interface_vente_ody_c_ines.Log.contactAuthenticationRequest inValue = new interface_vente_ody_c_ines.Log.contactAuthenticationRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.contactAuthenticationRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.request = request;
            interface_vente_ody_c_ines.Log.contactAuthenticationResponse retVal = ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).contactAuthentication(inValue);
            return retVal.Body.contactAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.contactAuthenticationResponse> interface_vente_ody_c_ines.Log.LoginSoap.contactAuthenticationAsync(interface_vente_ody_c_ines.Log.contactAuthenticationRequest request) {
            return base.Channel.contactAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.contactAuthenticationResponse> contactAuthenticationAsync(string sessionId, interface_vente_ody_c_ines.Log.AuthContact request) {
            interface_vente_ody_c_ines.Log.contactAuthenticationRequest inValue = new interface_vente_ody_c_ines.Log.contactAuthenticationRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.contactAuthenticationRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.request = request;
            return ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).contactAuthenticationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        interface_vente_ody_c_ines.Log.contactChangePasswordResponse interface_vente_ody_c_ines.Log.LoginSoap.contactChangePassword(interface_vente_ody_c_ines.Log.contactChangePasswordRequest request) {
            return base.Channel.contactChangePassword(request);
        }
        
        public interface_vente_ody_c_ines.Log.CodeEnum contactChangePassword(string sessionId, int contactReference, string password, string newPassword) {
            interface_vente_ody_c_ines.Log.contactChangePasswordRequest inValue = new interface_vente_ody_c_ines.Log.contactChangePasswordRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.contactChangePasswordRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.contactReference = contactReference;
            inValue.Body.password = password;
            inValue.Body.newPassword = newPassword;
            interface_vente_ody_c_ines.Log.contactChangePasswordResponse retVal = ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).contactChangePassword(inValue);
            return retVal.Body.contactChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.contactChangePasswordResponse> interface_vente_ody_c_ines.Log.LoginSoap.contactChangePasswordAsync(interface_vente_ody_c_ines.Log.contactChangePasswordRequest request) {
            return base.Channel.contactChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<interface_vente_ody_c_ines.Log.contactChangePasswordResponse> contactChangePasswordAsync(string sessionId, int contactReference, string password, string newPassword) {
            interface_vente_ody_c_ines.Log.contactChangePasswordRequest inValue = new interface_vente_ody_c_ines.Log.contactChangePasswordRequest();
            inValue.Body = new interface_vente_ody_c_ines.Log.contactChangePasswordRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.contactReference = contactReference;
            inValue.Body.password = password;
            inValue.Body.newPassword = newPassword;
            return ((interface_vente_ody_c_ines.Log.LoginSoap)(this)).contactChangePasswordAsync(inValue);
        }
    }
}
